[package]
name = "parcoursdb"
version = "0.1.0"
authors = ["Paul Kirkwood <paul@paulandsue.plus.com>"]
edition = "2018"

[lib]
name = "parcoursdb"

[dependencies]
bitflags = "1.2.1"
chrono = "0.4"
regex = "1.3.4"
